# Generated by Django 3.1.4 on 2021-01-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210113_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
