# Generated by Django 3.1.4 on 2020-12-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201214_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.FileField(null=True, upload_to='images/products_img'),
        ),
    ]
